version: 2.1

jobs:
  build-and-test:

    docker:
      - image: cimg/node:14.15.4
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD

    steps:

      - checkout

      - restore_cache:
          keys:
            - node-dependencies-v1-{{ .Branch }}-{{ checksum "application/package-lock.json" }}

      - run:
          name: Install dependencies
          command: |
            cd application
            npm install

      - save_cache:
          key: node-dependencies-v1-{{ .Branch }}-{{ checksum "application/package-lock.json" }}
          paths:
            - application/node_modules
            - ~/.npm
            - ~/.cache
      
      - run:
          name: Run unit tests
          command: |
            cd application
            npm test

workflows:
  build-and-test-app:
    jobs:

      # all commits run unit tests
      - build-and-test:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
