version: 2.1

jobs:
  build-and-test:

    docker:
      - image: cimg/node:14.15.4
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD

    steps:

      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "application/package.json" }}

      - run:
          name: Install dependencies
          command: |
            cd application
            npm ci

      - save_cache:
          key: v1-dependencies-{{ checksum "application/package.json" }}
          paths:
            - application/node_modules
            - application/.npm
            - application/.cache
      
      - run:
          name: Run unit tests
          command: |
            cd application
            npm test

workflows:
  build-and-test-app:
    jobs:

      # all commits run unit tests
      - build-and-test:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
